# Generated by Django 4.1.4 on 2023-02-07 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(
                max_length=10,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
