# Generated by Django 4.1.3 on 2022-11-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_location_alter_ad_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="location",),
        migrations.AddField(
            model_name="user",
            name="locations",
            field=models.ManyToManyField(to="ads.location"),
        ),
    ]
