# Generated by Django 4.1.3 on 2022-11-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_remove_user_location_user_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
